package br.com.sisnema.syslocadora.model;

// Generated 29/01/2014 22:23:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChequeId generated by hbm2java
 */
@Embeddable
public class ChequeId implements java.io.Serializable {

	private int conta;
	private int cheque;

	public ChequeId() {
	}

	public ChequeId(int conta, int cheque) {
		this.conta = conta;
		this.cheque = cheque;
	}

	@Column(name = "conta", nullable = false)
	public int getConta() {
		return this.conta;
	}

	public void setConta(int conta) {
		this.conta = conta;
	}

	@Column(name = "cheque", nullable = false)
	public int getCheque() {
		return this.cheque;
	}

	public void setCheque(int cheque) {
		this.cheque = cheque;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChequeId))
			return false;
		ChequeId castOther = (ChequeId) other;

		return (this.getConta() == castOther.getConta())
				&& (this.getCheque() == castOther.getCheque());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getConta();
		result = 37 * result + this.getCheque();
		return result;
	}

}
