package br.com.sisnema.syslocadora.model;

// Generated 29/01/2014 22:23:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsuarioPermissao generated by hbm2java
 */
@Entity
@Table(name = "usuario_permissao", catalog = "agenda", uniqueConstraints = @UniqueConstraint(columnNames = {
		"usuario", "permissao" }))
public class UsuarioPermissao implements java.io.Serializable {

	private UsuarioPermissaoId id;
	private Usuario usuario;

	public UsuarioPermissao() {
	}

	public UsuarioPermissao(UsuarioPermissaoId id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "usuario", column = @Column(name = "usuario", nullable = false)),
			@AttributeOverride(name = "permissao", column = @Column(name = "permissao", length = 50)) })
	public UsuarioPermissaoId getId() {
		return this.id;
	}

	public void setId(UsuarioPermissaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
