package br.com.sisnema.syslocadora.model;

// Generated 29/01/2014 22:23:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "agenda", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
public class Usuario implements java.io.Serializable {

	private Integer codigo;
	private boolean ativo;
	private String celular;
	private String email;
	private String idioma;
	private String login;
	private Date nascimento;
	private String nome;
	private String senha;
	private Set<UsuarioPermissao> usuarioPermissaos = new HashSet<UsuarioPermissao>(
			0);
	private Set<Lancamento> lancamentos = new HashSet<Lancamento>(0);
	private Set<Acao> acaos = new HashSet<Acao>(0);
	private Set<ContaBancaria> contaBancarias = new HashSet<ContaBancaria>(0);
	private Set<Categoria> categorias = new HashSet<Categoria>(0);

	public Usuario() {
	}

	public Usuario(boolean ativo) {
		this.ativo = ativo;
	}

	public Usuario(boolean ativo, String celular, String email, String idioma,
			String login, Date nascimento, String nome, String senha,
			Set<UsuarioPermissao> usuarioPermissaos,
			Set<Lancamento> lancamentos, Set<Acao> acaos,
			Set<ContaBancaria> contaBancarias, Set<Categoria> categorias) {
		this.ativo = ativo;
		this.celular = celular;
		this.email = email;
		this.idioma = idioma;
		this.login = login;
		this.nascimento = nascimento;
		this.nome = nome;
		this.senha = senha;
		this.usuarioPermissaos = usuarioPermissaos;
		this.lancamentos = lancamentos;
		this.acaos = acaos;
		this.contaBancarias = contaBancarias;
		this.categorias = categorias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@Column(name = "ativo", nullable = false)
	public boolean isAtivo() {
		return this.ativo;
	}

	public void setAtivo(boolean ativo) {
		this.ativo = ativo;
	}

	@Column(name = "celular")
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "idioma")
	public String getIdioma() {
		return this.idioma;
	}

	public void setIdioma(String idioma) {
		this.idioma = idioma;
	}

	@Column(name = "login", unique = true)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "nascimento", length = 19)
	public Date getNascimento() {
		return this.nascimento;
	}

	public void setNascimento(Date nascimento) {
		this.nascimento = nascimento;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "senha")
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioPermissao> getUsuarioPermissaos() {
		return this.usuarioPermissaos;
	}

	public void setUsuarioPermissaos(Set<UsuarioPermissao> usuarioPermissaos) {
		this.usuarioPermissaos = usuarioPermissaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Lancamento> getLancamentos() {
		return this.lancamentos;
	}

	public void setLancamentos(Set<Lancamento> lancamentos) {
		this.lancamentos = lancamentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Acao> getAcaos() {
		return this.acaos;
	}

	public void setAcaos(Set<Acao> acaos) {
		this.acaos = acaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<ContaBancaria> getContaBancarias() {
		return this.contaBancarias;
	}

	public void setContaBancarias(Set<ContaBancaria> contaBancarias) {
		this.contaBancarias = contaBancarias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Categoria> getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Set<Categoria> categorias) {
		this.categorias = categorias;
	}

}
