package br.com.sisnema.syslocadora.model;

// Generated 29/01/2014 22:23:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioPermissaoId generated by hbm2java
 */
@Embeddable
public class UsuarioPermissaoId implements java.io.Serializable {

	private int usuario;
	private String permissao;

	public UsuarioPermissaoId() {
	}

	public UsuarioPermissaoId(int usuario) {
		this.usuario = usuario;
	}

	public UsuarioPermissaoId(int usuario, String permissao) {
		this.usuario = usuario;
		this.permissao = permissao;
	}

	@Column(name = "usuario", nullable = false)
	public int getUsuario() {
		return this.usuario;
	}

	public void setUsuario(int usuario) {
		this.usuario = usuario;
	}

	@Column(name = "permissao", length = 50)
	public String getPermissao() {
		return this.permissao;
	}

	public void setPermissao(String permissao) {
		this.permissao = permissao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioPermissaoId))
			return false;
		UsuarioPermissaoId castOther = (UsuarioPermissaoId) other;

		return (this.getUsuario() == castOther.getUsuario())
				&& ((this.getPermissao() == castOther.getPermissao()) || (this
						.getPermissao() != null
						&& castOther.getPermissao() != null && this
						.getPermissao().equals(castOther.getPermissao())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUsuario();
		result = 37 * result
				+ (getPermissao() == null ? 0 : this.getPermissao().hashCode());
		return result;
	}

}
